services:
  # Database
  infrastructure_repositories:
    namespace: App\Infrastructure\Model\
    resource: '../../../../../../../../src/Infrastructure/Model/**/Doctrine/*Repository.php'
    tags: [ infrastructure_repository ]

  Doctrine\ORM\EntityManager:
    factory: [ App\Infrastructure\Persistence\Doctrine\EntityManagerFactory, build ]
    arguments:
      - driver: '%env(DATABASE_DRIVER)%'
        host: '%env(DATABASE_HOST)%'
        port: '%env(DATABASE_PORT)%'
        dbname: '%env(DATABASE_NAME)%'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
      - '%env(APP_ENV)%'
    tags:
      - { name: 'db_connection' }
    public: true

  App\Domain\User\IUserRepository:
    alias: 'App\Infrastructure\Model\User\InMemory\DoctrineUserRepository'
    public: true